### ISSUE TITLE
Suggestion: set 'empty' to true by default

### ISSUE THREAD

**Issue by filipedeschamps** [jonathanepollack/gulp-minify-html#16]
@jonathanepollack how are you?

Very nice gulp plugin, I'm loving it. May I suggest only one thing? Change the `empty` option to true by default.

When you build an application with Angular, it's very common to have `directives` in the format of empty attributes. I almost filled a bug in ui-router because of this situation:

```html
<!-- UI-Router named views worked as expected -->
<div ui-view="namedView"></div>
```

```html
<!-- Nested views as attribute didn't work -->
<div ui-view></div>
```

```html
<!-- Nested views as elements worked -->
<ui-view />
```

I lost a lot of time until I noticed the compiled version didn't have the attribute anymore.

So, it's only a suggestion, I'm sure it will bite other noobs like me :)

Also I'm glad there's a way to prevent this behavior.

Best regards.

**Comment by 2is10** [comment]
Agreed. Any minification tool should be safe (preserve function of original code) by default. 

This isn’t just an angular issue. The HTML specification defines the semantics for attributes with no values and suggests using this syntax for boolean attributes like `checked` and `disabled`.
https://html.spec.whatwg.org/multipage/syntax.html#attributes-2 (see **Empty Attribute Syntax**)
https://html.spec.whatwg.org/multipage/infrastructure.html#boolean-attributes (see examples)

**Comment by jonathanepollack** [comment]
1) @filipedeschamps: sorry for not responding sooner!

2) While I agree with the line:

> Any minification tool should be safe (preserve function of original code) by default.

I feel obliged to keep the original [`minimize`](https://github.com/Moveo/minimize) API, as this is nothing but a thin wrapper around it. That's kind of the spirit of this plug in. That said, I think it would be cool to bring this up with the minimize crew and see what they have to say. I think it's a good argument.
